window.BZ = window.BZ || {};
BZ.UI={
 el:{},
 init(off){
  const ids=['currencies','teamPower','partyList','activeStandMini','fateFill','fateText','fateLuck','partEyebrow','locationName','waveText','bossRibbon','enemyTag','enemyButton','enemyGlyph','enemyName','hpText','hpFill','shieldFill','statusRow','damageLayer','comboBadge','abilityRow','autoToggle','autoState','arrowBtn','arrowCount','quickUpgrades','eventFeed','bottomNav','drawer','drawerBody','drawerTitle','drawerEyebrow','drawerClose','audioBtn','saveBtn','bossRushBtn','offlineModal','offlineStats','offlineClaim','revealModal','revealType','revealName','revealDesc','revealClose','combatCard','toastStack'];ids.forEach(id=>this.el[id]=document.getElementById(id));
  this.bind();this.renderAll();if(off)this.showOffline(off);
 },
 bind(){
  this.el.enemyButton.onclick=()=>BZ.attack();
  document.addEventListener('keydown',e=>{if(['INPUT','TEXTAREA'].includes(document.activeElement.tagName))return;if(e.code==='Space'){e.preventDefault();BZ.attack()}if(e.key==='1')BZ.useAbility(1);if(e.key==='2')BZ.useAbility(2);if(e.key==='3')BZ.useAbility(3)});
  this.el.bottomNav.onclick=e=>{const b=e.target.closest('[data-tab]');if(b)this.openTab(b.dataset.tab)};
  document.querySelectorAll('[data-tab]').forEach(b=>b.addEventListener('click',()=>this.openTab(b.dataset.tab)));
  this.el.drawerClose.onclick=()=>this.closeDrawer();
  this.el.autoToggle.onclick=()=>{if(!BZ.state.autoUnlocked){this.toast('LOCKED','Reach Level 5 to unlock Auto Attack.');return}BZ.state.autoAttack=!BZ.state.autoAttack;this.renderNumbers()};
  this.el.bossRushBtn.onclick=()=>{BZ.state.bossPush=!BZ.state.bossPush;this.toast('BOSS PUSH',BZ.state.bossPush?'Enabled.':'Disabled.')};
  this.el.arrowBtn.onclick=()=>BZ.rollStand();
  this.el.audioBtn.onclick=()=>{BZ.state.settings.audio=!BZ.state.settings.audio;this.el.audioBtn.textContent=BZ.state.settings.audio?'♪':'×';if(BZ.state.settings.audio)BZ.tone(440,.08)};
  this.el.saveBtn.onclick=()=>BZ.save(BZ.state,true);
  this.el.offlineClaim.onclick=()=>this.el.offlineModal.classList.add('hidden');
  this.el.revealClose.onclick=()=>this.el.revealModal.classList.add('hidden');
 },
 renderAll(){this.renderNumbers();this.renderParty();this.renderCombat();this.renderAbilities();this.renderUpgrades();this.renderFeed();if(!this.el.drawer.classList.contains('hidden'))this.renderDrawer()},
 renderNumbers(){
  const s=BZ.state;
  const cur=[['¥','Yen',BZ.fmt(s.yen)],['➶','Arrows',s.arrows],['★','Legacy',s.legacy],['∞','Heaven',s.heaven]];
  this.el.currencies.innerHTML=cur.map(x=>`<div class="currency"><small>${x[1]}</small><b><i>${x[0]}</i>${x[2]}</b></div>`).join('');
  this.el.teamPower.textContent=BZ.fmt(BZ.partyPower())+' PWR';
  const f=Math.min(100,(s.questProgress.fate||0)%101);this.el.fateFill.style.width=f+'%';this.el.fateText.textContent=Math.floor(f)+' / 100';this.el.fateLuck.textContent='Luck ×'+(1+Math.min(.5,s.fatePoints*.01)).toFixed(2);
  this.el.autoState.textContent=s.autoUnlocked?(s.autoAttack?'Enabled':'Disabled'):'Locked';this.el.autoToggle.classList.toggle('on',s.autoAttack);this.el.arrowCount.textContent=`${s.arrows} available`;
  this.el.comboBadge.textContent='COMBO ×'+(1+Math.min(s.combo,100)*.012).toFixed(2);
 },
 renderParty(){
  const s=BZ.state;this.el.partyList.innerHTML=s.party.map(id=>{const c=BZ.getChar(id);if(!c)return'';return`<div class="party-member"><div class="portrait">${c.glyph}</div><div class="member-meta"><b>${c.name}</b><small>${c.role}</small></div><div class="member-lvl">Lv.${BZ.charLevel(id)}</div></div>`}).join('')||'<div class="feed-item">No active party.</div>';
  const st=BZ.getStand(s.activeStand);this.el.activeStandMini.innerHTML=st?`<div class="stand-mini"><b>${st.name}</b><small>Lv.${BZ.standLevel(st.id)} • PWR ${st.power} • SPD ${st.speed}</small></div>`:'<div class="stand-mini"><b>No Stand</b><small>Use an Arrow to awaken one.</small></div>';
 },
 renderCombat(){
  const s=BZ.state,p=BZ.getPart();document.getElementById('app').className='part-'+s.part;this.el.partEyebrow.textContent=`PART ${p.id} • ${p.name}`;this.el.locationName.textContent=p.location;this.el.waveText.textContent=`${s.wave} / 30`;this.el.enemyName.textContent=s.enemy.name;this.el.enemyGlyph.textContent=s.enemy.glyph;this.el.enemyTag.textContent=s.enemy.tag;this.el.bossRibbon.classList.toggle('hidden',!s.enemy.boss);this.renderCombatBars();
 },
 renderCombatBars(){const s=BZ.state;const pct=Math.max(0,Math.min(100,s.enemy.hp/s.enemy.maxHp*100));this.el.hpFill.style.width=pct+'%';this.el.hpText.textContent=`${BZ.fmt(s.enemy.hp)} / ${BZ.fmt(s.enemy.maxHp)}`;this.el.shieldFill.style.width=(s.enemy.maxShield?Math.max(0,s.enemy.shield/s.enemy.maxHp*100):0)+'%';const st=[];if(s.statuses.timeStop>0)st.push('⏱ TIME STOP');if(s.statuses.defBreak>0)st.push('⬇ DEFENSE');if(s.statuses.burn>0)st.push('🔥 BURN');if(s.statuses.spin>0)st.push('⟳ SPIN');this.el.statusRow.innerHTML=st.map(x=>`<span class="status">${x}</span>`).join('')},
 renderAbilities(){
  const s=BZ.state,stand=BZ.getStand(s.activeStand);const names=[stand?.skill||'Hamon Rush','Precision Break',stand?.ultimate||'Overdrive'];const desc=['Rapid multi-hit active attack.','Heavy strike + defense reduction.','Massive burst and time distortion.'];const cds=[6,13,28];this.el.abilityRow.innerHTML=names.map((n,i)=>{const k='a'+(i+1),left=s.cooldowns[k]||0,pct=Math.max(0,Math.min(100,left/cds[i]*100));return`<button class="ability" data-ab="${i+1}" ${left>0?'disabled':''}><span class="key">${i+1}</span><b>${n}</b><small>${left>0?left.toFixed(1)+'s':desc[i]}</small>${left>0?`<i class="cd" style="width:${pct}%"></i>`:''}</button>`}).join('');this.el.abilityRow.querySelectorAll('[data-ab]').forEach(b=>b.onclick=()=>BZ.useAbility(+b.dataset.ab))
 },
 renderUpgrades(){this.el.quickUpgrades.innerHTML=BZ.UPGRADES.slice(0,4).map(u=>{const l=BZ.state.upgrades[u.id],cost=BZ.upgradeCost(u.id);return`<div class="upgrade"><div class="upgrade-head"><b>${u.name}</b><span>Lv.${l}</span></div><p>${u.desc}</p><button data-up="${u.id}" ${BZ.state.yen<cost?'disabled':''}>BUY • ¥${BZ.fmt(cost)}</button></div>`}).join('');this.el.quickUpgrades.querySelectorAll('[data-up]').forEach(b=>b.onclick=()=>BZ.upgrade(b.dataset.up))},
 renderFeed(){this.el.eventFeed.innerHTML=BZ.state.feed.map(x=>`<div class="feed-item ${x.type}">${x.html}</div>`).join('')||'<div class="feed-item">Your bizarre journey has begun.</div>'},
 frame(){this.renderCombatBars();this.renderAbilities();this.renderNumbers()},
 hit(crit){if(BZ.state.settings.shake){this.el.combatCard.classList.remove('shake');void this.el.combatCard.offsetWidth;this.el.combatCard.classList.add('shake')}if(crit){this.el.combatCard.classList.remove('flash');void this.el.combatCard.offsetWidth;this.el.combatCard.classList.add('flash')}this.el.enemyGlyph.classList.add('hit');setTimeout(()=>this.el.enemyGlyph.classList.remove('hit'),70)},
 damage(n,crit){if(!BZ.state.settings.damageNumbers)return;const d=document.createElement('div');d.className='dmg'+(crit?' crit':'');d.textContent=(crit?'CRIT ':'')+BZ.fmt(n);d.style.left=(42+Math.random()*16)+'%';d.style.top=(34+Math.random()*15)+'%';this.el.damageLayer.appendChild(d);setTimeout(()=>d.remove(),750)},
 toast(title,text){const t=document.createElement('div');t.className='toast';t.innerHTML=`<b>${title}</b><small>${text}</small>`;this.el.toastStack.appendChild(t);setTimeout(()=>t.remove(),3200)},
 reveal(type,name,desc){this.el.revealType.textContent=type;this.el.revealName.textContent=name;this.el.revealDesc.textContent=desc;this.el.revealModal.classList.remove('hidden');BZ.tone(660,.22,'sawtooth')},
 showOffline(o){const rows=[['Time Away',this.time(o.away)],['Effective Idle',this.time(o.secs)],['Enemies Defeated',BZ.fmt(o.kills)],['Yen Earned','¥'+BZ.fmt(o.yen)],['XP Earned',BZ.fmt(o.xp)],['Rare Events','Fate protected your run']];this.el.offlineStats.innerHTML=rows.map(x=>`<div class="offline-stat"><small>${x[0]}</small><b>${x[1]}</b></div>`).join('');this.el.offlineModal.classList.remove('hidden')},
 time(sec){const h=Math.floor(sec/3600),m=Math.floor(sec%3600/60);return h?`${h}h ${m}m`:`${m}m`},
 openTab(tab){document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));if(tab==='fight'){this.closeDrawer();return}this.el.drawer.classList.remove('hidden');this.el.drawer.dataset.tab=tab;this.renderDrawer()},closeDrawer(){this.el.drawer.classList.add('hidden');document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.tab==='fight'))},
 renderDrawer(){const tab=this.el.drawer.dataset.tab;const map={characters:['ROSTER','Characters'],stands:['STAND SYSTEM','Stands'],parts:['WORLD MAP','Parts'],quests:['FATE OBJECTIVES','Quests & Achievements'],prestige:['ASCENSION','Prestige'],collection:['RELIC VAULT','Collection'],settings:['SYSTEM','Settings']};const m=map[tab]||['SYSTEM','Menu'];this.el.drawerEyebrow.textContent=m[0];this.el.drawerTitle.textContent=m[1];if(tab==='characters')this.drawCharacters();if(tab==='stands')this.drawStands();if(tab==='parts')this.drawParts();if(tab==='quests')this.drawQuests();if(tab==='prestige')this.drawPrestige();if(tab==='collection')this.drawCollection();if(tab==='settings')this.drawSettings()},
 drawCharacters(){const s=BZ.state;this.el.drawerBody.innerHTML=`<div class="section-title">Build a party of up to 6</div><div class="section-sub">Roles and synergies matter more than rarity. Tap a recruited unit to add/remove it.</div><div class="grid">${BZ.CHARACTERS.map(c=>{const unlocked=s.unlockedCharacters.includes(c.id),selected=s.party.includes(c.id),lvl=BZ.charLevel(c.id),cost=35*c.base*Math.pow(1.19,lvl-1);return`<article class="card ${unlocked?'':'locked'} ${selected?'selected':''}"><span class="rarity">${c.rarity} • PART ${c.part}</span><h3>${c.name}</h3><p>${c.passive}</p><div class="card-stats"><span>Role <b>${c.role}</b></span><span>Lv <b>${lvl}</b></span><span>Base <b>${BZ.fmt(c.base)}</b></span></div><div class="card-actions">${unlocked?`<button data-team="${c.id}" class="${selected?'primary':''}">${selected?'ACTIVE':'ADD TEAM'}</button><button data-clvl="${c.id}" ${s.yen<cost?'disabled':''}>LVL ¥${BZ.fmt(cost)}</button>`:'<button disabled>LOCKED</button>'}</div></article>`}).join('')}</div>`;this.el.drawerBody.querySelectorAll('[data-team]').forEach(b=>b.onclick=()=>{const id=b.dataset.team,p=s.party,idx=p.indexOf(id);if(idx>=0)p.splice(idx,1);else if(p.length<6)p.push(id);else return this.toast('PARTY FULL','Remove a unit first.');this.renderAll()});this.el.drawerBody.querySelectorAll('[data-clvl]').forEach(b=>b.onclick=()=>{BZ.levelChar(b.dataset.clvl);this.drawCharacters()})},
 drawStands(){const s=BZ.state;this.el.drawerBody.innerHTML=`<div class="section-title">Stand Collection</div><div class="section-sub">Stand Arrows awaken base Stands. Evolution forms require level + boss challenges.</div><div style="display:flex;gap:8px;margin-bottom:14px"><button class="wide-btn" id="drawerArrow">USE STAND ARROW (${s.arrows})</button></div><div class="grid">${BZ.STANDS.map(st=>{const unlocked=s.unlockedStands.includes(st.id),lvl=BZ.standLevel(st.id),cost=120*st.power*Math.pow(1.22,lvl-1);return`<article class="card ${unlocked?'':'locked'} ${s.activeStand===st.id?'selected':''}"><span class="rarity">${st.rarity} • PART ${st.part}</span><h3>${st.name}</h3><p>${st.passive}</p><div class="card-stats"><span>PWR <b>${st.power}</b></span><span>SPD <b>${st.speed}</b></span><span>Lv <b>${lvl}</b></span></div><div class="card-actions">${unlocked?`<button data-equip="${st.id}" class="${s.activeStand===st.id?'primary':''}">${s.activeStand===st.id?'EQUIPPED':'EQUIP'}</button><button data-slvl="${st.id}" ${s.yen<cost?'disabled':''}>LVL ¥${BZ.fmt(cost)}</button>${st.evolves?`<button data-evolve="${st.id}">EVOLVE</button>`:''}`:'<button disabled>UNKNOWN</button>'}</div></article>`}).join('')}</div>`;document.getElementById('drawerArrow').onclick=()=>BZ.rollStand();this.el.drawerBody.querySelectorAll('[data-equip]').forEach(b=>b.onclick=()=>{s.activeStand=b.dataset.equip;this.renderAll()});this.el.drawerBody.querySelectorAll('[data-slvl]').forEach(b=>b.onclick=()=>{BZ.levelStand(b.dataset.slvl);this.drawStands()});this.el.drawerBody.querySelectorAll('[data-evolve]').forEach(b=>b.onclick=()=>{BZ.evolveStand(b.dataset.evolve);this.drawStands()})},
 drawParts(){const s=BZ.state;this.el.drawerBody.innerHTML=`<div class="section-title">Travel the JoJo eras</div><div class="section-sub">Each Part has 30 encounters, distinct bosses, resources and mechanics.</div><div class="grid">${BZ.PARTS.map(p=>{const unlocked=p.id<=s.unlockedPart,done=s.completedParts.includes(p.id),prog=p.id===s.part?Math.min(100,(s.wave-1)/30*100):(done?100:0);return`<article class="card part-card ${unlocked?'':'locked'} ${s.part===p.id?'selected':''}"><div class="part-num">${p.id}</div><span class="rarity">PART ${p.id}</span><h3>${p.name}</h3><p>${p.location} • ${p.mechanic}<br>${p.bosses.join(' • ')}</p><div class="progress"><i style="width:${prog}%"></i></div><div class="card-actions"><button data-part="${p.id}" ${unlocked?'':'disabled'}>${s.part===p.id?'CURRENT':unlocked?'TRAVEL':'LOCKED'}</button></div></article>`}).join('')}</div>`;this.el.drawerBody.querySelectorAll('[data-part]').forEach(b=>b.onclick=()=>{BZ.travelTo(+b.dataset.part);this.closeDrawer()})},
 drawQuests(){const s=BZ.state;this.el.drawerBody.innerHTML=`<div class="section-title">Quests</div><div class="grid">${BZ.QUESTS.map(q=>{const p=Math.min(q.goal,s.questProgress[q.id]||0),done=p>=q.goal,claimed=s.claimedQuests.includes(q.id);return`<article class="card quest"><div><span class="rarity">${claimed?'CLAIMED':done?'COMPLETE':'ACTIVE'}</span><h3>${q.name}</h3><p>${q.desc}</p><div class="progress"><i style="width:${p/q.goal*100}%"></i></div><small>${BZ.fmt(p)} / ${BZ.fmt(q.goal)}</small></div><div><div class="reward">${Object.entries(q.reward).map(([k,v])=>`${k} +${v}`).join('<br>')}</div><div class="card-actions" style="margin-top:10px"><button data-claim="${q.id}" ${!done||claimed?'disabled':''}>CLAIM</button></div></div></article>`}).join('')}</div><div class="section-title" style="margin-top:24px">Achievements</div><div class="grid">${BZ.ACHIEVEMENTS.map(a=>`<article class="card achievement ${s.achievements.includes(a.id)?'done':''}"><span class="rarity">${s.achievements.includes(a.id)?'UNLOCKED':'LOCKED'}</span><h3>${a.name}</h3><p>${a.desc}</p></article>`).join('')}</div>`;this.el.drawerBody.querySelectorAll('[data-claim]').forEach(b=>b.onclick=()=>{BZ.claimQuest(b.dataset.claim);this.drawQuests()})},
 drawPrestige(){const s=BZ.state,g=BZ.rebirthGain();this.el.drawerBody.innerHTML=`<div class="prestige-hero"><span class="eyebrow">REBIRTH</span><h3>Joestar Legacy</h3><p>Reset basic Yen, levels, upgrades and waves. Keep unlocked Parts, Stands, relics and achievements. Legacy permanently multiplies almost every route.</p><div class="card-stats"><span>Current <b>${s.legacy}</b></span><span>Gain now <b>+${g}</b></span><span>Multiplier <b>×${BZ.legacyMult().toFixed(2)}</b></span></div><button class="wide-btn" id="rebirthBtn">REBIRTH FOR +${g} LEGACY</button></div><div class="grid"><article class="card"><span class="rarity">LAYER 2</span><h3>Stand Awakening</h3><p>Level and evolve Stands to unlock permanent Stand-focused power. Evolutions are challenge-gated, not cash-gated.</p></article><article class="card ${s.completedParts.length<1?'locked':''}"><span class="rarity">LAYER 3</span><h3>Timeline Reset</h3><p>Complete Parts to accumulate Fate and route-specific permanent bonuses.</p></article><article class="card ${s.unlockedPart<6?'locked':''}"><span class="rarity">LAYER 4</span><h3>Heaven Ascension</h3><p>Late-game universal reset. Becomes meaningful after the Stone Ocean route.</p></article><article class="card ${s.unlockedPart<9?'locked':''}"><span class="rarity">ENDGAME</span><h3>Infinite Rotation</h3><p>Multiverse scaling, Dimension Shards and absurd build combinations await after all Parts.</p></article></div>`;document.getElementById('rebirthBtn').onclick=()=>BZ.rebirth()},
 drawCollection(){const s=BZ.state;this.el.drawerBody.innerHTML=`<div class="section-title">Relics</div><div class="section-sub">Rare drops dramatically alter builds. Only one relic is equipped at a time in this release.</div><div class="grid">${BZ.ITEMS.map(i=>{const got=s.items.includes(i.id);return`<article class="card ${got?'':'locked'} ${s.equippedItem===i.id?'selected':''}"><span class="rarity">${i.rarity}</span><h3>${i.name}</h3><p>${i.desc}</p><div class="card-actions"><button data-item="${i.id}" ${got?'':'disabled'}>${s.equippedItem===i.id?'EQUIPPED':got?'EQUIP':'UNKNOWN'}</button></div></article>`}).join('')}</div>`;this.el.drawerBody.querySelectorAll('[data-item]').forEach(b=>b.onclick=()=>{BZ.equipItem(b.dataset.item);this.drawCollection()})},
 drawSettings(){const s=BZ.state;const opts=[['audio','Original SFX'],['particles','Particles'],['shake','Screen shake'],['damageNumbers','Damage numbers'],['autosave','Autosave'],['performance','Performance mode']];this.el.drawerBody.innerHTML=`<div class="settings-grid">${opts.map(([k,n])=>`<div class="setting"><label><span>${n}</span><input type="checkbox" data-set="${k}" ${s.settings[k]?'checked':''}></label></div>`).join('')}</div><div class="section-title" style="margin-top:24px">Save Tools</div><div class="settings-grid"><div class="setting"><label>Export / Import</label><textarea class="savebox" id="saveBox" placeholder="Exported save appears here, or paste one to import."></textarea><div class="card-actions" style="margin-top:8px"><button id="exportBtn">EXPORT</button><button id="importBtn">IMPORT</button></div></div><div class="setting"><label>Danger Zone</label><p class="section-sub" style="margin-top:10px">Hard reset permanently deletes this browser save.</p><div class="card-actions"><button id="resetBtn">HARD RESET</button></div></div></div>`;this.el.drawerBody.querySelectorAll('[data-set]').forEach(i=>i.onchange=()=>{s.settings[i.dataset.set]=i.checked;BZ.save(s)});document.getElementById('exportBtn').onclick=()=>document.getElementById('saveBox').value=BZ.exportSave(s);document.getElementById('importBtn').onclick=()=>{try{BZ.state=BZ.importSave(document.getElementById('saveBox').value);BZ.spawnEnemy();BZ.save(BZ.state);this.renderAll();this.toast('SAVE IMPORTED','Your timeline has been restored.')}catch(e){this.toast('IMPORT FAILED','That save string is invalid.')}};document.getElementById('resetBtn').onclick=()=>{if(confirm('Delete ALL Bizarre Legacy progress on this browser?')){localStorage.removeItem(BZ.SAVE_KEY);location.reload()}}}
};

document.addEventListener('DOMContentLoaded',()=>BZ.init());
