function updateLobbyUI(){const ps=Object.values(gameState?.players||{});$('#lobbyPlayers').innerHTML=ps.map(p=>`<div class="playerRow"><div class="avatar" style="background:${p.color||'#aaa'}">${esc((p.name||'?')[0].toUpperCase())}</div><div style="min-width:0"><div class="pname">${esc(p.name||'Player')}</div><div class="badge">${p.host?'HOST':p.bot?'BOT':'PLAYER'}</div></div></div>`).join('');$('#startBtn').disabled=ps.length<2;$('#addBotBtn').disabled=ps.length>=MAX_PLAYERS}
function updateInviteURL(){try{const u=new URL(location.href);u.searchParams.set('room',roomCode);history.replaceState(null,'',u)}catch{}}
function copyInvite(){let link;try{const u=new URL(location.href);u.searchParams.set('room',roomCode);link=u.toString()}catch{link=roomCode}if(navigator.clipboard?.writeText){navigator.clipboard.writeText(link).then(()=>toast('Invite link copied')).catch(()=>toast('Room code: '+roomCode))}else toast('Room code: '+roomCode)}

function sendInputMaybe(t){if(isHost||isSolo||!hostConn?.open)return;if(t-lastInputSend<32)return;lastInputSend=t;try{hostConn.send({type:'input',input:localInput})}catch{}}
function setAimFromPointer(e){const rect=canvas.getBoundingClientRect(),x=(e.clientX-rect.left)*(W/rect.width),y=(e.clientY-rect.top)*(H/rect.height);const p=gameState?.players?.[myId];if(p)localInput.aim=Math.atan2(y-p.y,x-p.x)}
function nearestAim(){const p=gameState?.players?.[myId];if(!p)return;let best=null,bd=1e18;for(const q of Object.values(gameState.players)){if(q.id===myId||!q.alive)continue;const d=dist2(p,q);if(d<bd){bd=d;best=q}}if(best)localInput.aim=Math.atan2(best.y-p.y,best.x-p.x)}
function keyUpdate(e,on){if(!gameScreen.classList.contains('active'))return;const tag=e.target?.tagName;if(tag==='INPUT'||tag==='TEXTAREA')return;const k=e.key.toLowerCase();if(['w','arrowup'].includes(k))localInput.up=on;if(['s','arrowdown'].includes(k))localInput.down=on;if(['a','arrowleft'].includes(k))localInput.left=on;if(['d','arrowright'].includes(k))localInput.right=on;if((k==='shift'||k===' ')&&on&&!e.repeat)localInput.dashSeq++;if(['w','a','s','d','arrowup','arrowdown','arrowleft','arrowright','shift',' '].includes(k)){e.preventDefault();ensureAudio()}sendInputMaybe(performance.now())}
window.addEventListener('keydown',e=>keyUpdate(e,true),{passive:false});window.addEventListener('keyup',e=>keyUpdate(e,false),{passive:false});
canvas.addEventListener('pointermove',e=>{setAimFromPointer(e);sendInputMaybe(performance.now())});canvas.addEventListener('pointerdown',e=>{if(e.button===0){ensureAudio();setAimFromPointer(e);localInput.fire=true;canvas.setPointerCapture?.(e.pointerId);sendInputMaybe(performance.now())}});canvas.addEventListener('pointerup',e=>{if(e.button===0){localInput.fire=false;sendInputMaybe(performance.now())}});canvas.addEventListener('pointercancel',()=>{localInput.fire=false});
setInterval(()=>sendInputMaybe(performance.now()),33);
$$('.touchBtn[data-key]').forEach(b=>{const prop=b.dataset.key;const down=e=>{e.preventDefault();ensureAudio();localInput[prop]=true;sendInputMaybe(performance.now())},up=e=>{e.preventDefault();localInput[prop]=false;sendInputMaybe(performance.now())};b.addEventListener('pointerdown',down);b.addEventListener('pointerup',up);b.addEventListener('pointercancel',up)});$('#touchFire').addEventListener('pointerdown',e=>{e.preventDefault();nearestAim();localInput.fire=true;sendInputMaybe(performance.now())});['pointerup','pointercancel'].forEach(ev=>$('#touchFire').addEventListener(ev,e=>{e.preventDefault();localInput.fire=false;sendInputMaybe(performance.now())}));$('#touchDash').addEventListener('pointerdown',e=>{e.preventDefault();localInput.dashSeq++;sendInputMaybe(performance.now())});

$('#hostBtn').addEventListener('click',hostRoom);$('#joinBtn').addEventListener('click',joinRoom);$('#soloBtn').addEventListener('click',startSolo);$('#roomInput').addEventListener('keydown',e=>{if(e.key==='Enter')joinRoom()});$('#roomInput').addEventListener('input',e=>e.target.value=cleanRoom(e.target.value));$('#addBotBtn').addEventListener('click',addBot);$('#startBtn').addEventListener('click',startRound);$('#copyBtn').addEventListener('click',copyInvite);$('#leaveLobbyBtn').addEventListener('click',leaveToHome);$('#leaveGameBtn').addEventListener('click',leaveToHome);$('#muteBtn').addEventListener('click',()=>{muted=!muted;$('#muteBtn').textContent=muted?'SOUND OFF':'SOUND ON';if(!muted)ensureAudio()});$('#rematchBtn').addEventListener('click',()=>{if(isHost||isSolo)startRound()});
window.addEventListener('beforeunload',cleanupNet);
try{const code=cleanRoom(new URL(location.href).searchParams.get('room'));if(code.length===5)$('#roomInput').value=code}catch{}
renderHUD(performance.now());
