function handleEvent(e){if(!e)return;if(e.kind==='shoot'){beep(e.weapon==='rocket'?'rocket':'shoot')}else if(e.kind==='hit'){beep('hit');if(e.player===myId){shake=Math.max(shake,6);flash=.35}}else if(e.kind==='pickup'){beep('pickup');if(e.player===myId)toast(String(e.pickupKind||'POWER').toUpperCase()+' PICKUP')}else if(e.kind==='kill'){beep('kill');shake=Math.max(shake,10);burst(e.x,e.y,24);const v=gameState?.players?.[e.victim]?.name||'Someone',k=e.killer?(gameState?.players?.[e.killer]?.name||'Someone'):'THE STORM';addFeed(k+' blasted '+v)}else if(e.kind==='boom'||e.kind==='meteor'){beep('rocket');shake=Math.max(shake,12);burst(e.x,e.y,34)}else if(e.kind==='dash'){beep('dash')}else if(e.kind==='roundEnd'){showEnd()}}
function addFeed(txt){feedItems.unshift({txt,until:performance.now()+4200});feedItems=feedItems.slice(0,5);renderFeed()}
function renderFeed(){const n=performance.now();feedItems=feedItems.filter(f=>f.until>n);$('#killfeed').innerHTML=feedItems.map(f=>`<div class="feed">${esc(f.txt)}</div>`).join('')}
function burst(x,y,n){for(let i=0;i<n;i++){const a=Math.random()*Math.PI*2,s=rand(50,280);particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:rand(.25,.7),r:rand(2,6)})}}
function centerMessage(msg,ms=1000){$('#centerMsg').textContent=msg;clearTimeout(centerTimer);centerTimer=setTimeout(()=>$('#centerMsg').textContent='',ms)}

function renderLoop(t){if(!gameState){renderRAF=0;return}const dt=Math.min(.05,(t-lastRender)/1000||.016);lastRender=t;draw(dt,t/1000);renderHUD(t);if(gameScreen.classList.contains('active'))renderRAF=requestAnimationFrame(renderLoop);else renderRAF=0}
function draw(dt,t){ctx.save();if(shake>0){ctx.translate(rand(-shake,shake),rand(-shake,shake));shake*=Math.pow(.08,dt)};ctx.fillStyle='#070a11';ctx.fillRect(-20,-20,W+40,H+40);
  ctx.strokeStyle='rgba(130,155,210,.075)';ctx.lineWidth=1;const gx=(t*20)%40;for(let x=-40+gx;x<W+40;x+=40){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,H);ctx.stroke()}for(let y=-40+gx;y<H+40;y+=40){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke()}
  const r=gameState.stormRadius||325;ctx.save();ctx.fillStyle='rgba(123,61,255,.18)';ctx.beginPath();ctx.rect(0,0,W,H);ctx.arc(CX,CY,r,0,Math.PI*2,true);ctx.fill('evenodd');ctx.restore();ctx.beginPath();ctx.arc(CX,CY,r,0,Math.PI*2);ctx.strokeStyle='rgba(168,117,255,.8)';ctx.lineWidth=4;ctx.shadowBlur=18;ctx.shadowColor='#9b6cff';ctx.stroke();ctx.shadowBlur=0;
  ctx.strokeStyle='rgba(255,255,255,.04)';ctx.lineWidth=2;for(const rr of [90,180,270]){ctx.beginPath();ctx.arc(CX,CY,rr,0,Math.PI*2);ctx.stroke()}
  for(const m of gameState.meteors||[]){const pulse=.72+.18*Math.sin(t*12);ctx.beginPath();ctx.arc(m.x,m.y,95*pulse,0,Math.PI*2);ctx.fillStyle='rgba(255,83,73,.08)';ctx.fill();ctx.strokeStyle='rgba(255,92,80,.82)';ctx.setLineDash([10,8]);ctx.lineWidth=4;ctx.stroke();ctx.setLineDash([]);ctx.fillStyle='#ff6b52';ctx.font='900 24px system-ui';ctx.textAlign='center';ctx.fillText('!',m.x,m.y+8)}
  for(const u of gameState.pickups||[]){ctx.save();ctx.translate(u.x,u.y);ctx.rotate(t*1.6+u.id);ctx.shadowBlur=18;ctx.shadowColor=PICKUP_COLORS[u.kind]||'#fff';ctx.fillStyle=PICKUP_COLORS[u.kind]||'#fff';roundRect(ctx,-16,-16,32,32,8);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='#10131d';ctx.font='900 13px system-ui';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(u.kind==='rapid'?'R':u.kind==='scatter'?'S':u.kind==='rocket'?'🚀':u.kind==='shield'?'◆':'+',0,1);ctx.restore()}
  for(const b of gameState.projectiles||[]){ctx.save();ctx.translate(b.x,b.y);ctx.fillStyle=b.rocket?'#ff7b4a':'#fff2a8';ctx.shadowBlur=b.rocket?18:10;ctx.shadowColor=ctx.fillStyle;ctx.beginPath();ctx.arc(0,0,b.radius||4,0,Math.PI*2);ctx.fill();ctx.restore()}
  const seen=new Set();for(const p of Object.values(gameState.players||{})){seen.add(p.id);let v=visualPlayers.get(p.id);if(!v){v={x:p.x||CX,y:p.y||CY};visualPlayers.set(p.id,v)}const alpha=p.id===myId&&isHost?1:1-Math.pow(.0008,dt);v.x+=(p.x-v.x)*alpha;v.y+=(p.y-v.y)*alpha;drawPlayer(p,v,t)}for(const id of visualPlayers.keys())if(!seen.has(id))visualPlayers.delete(id);
  for(let i=particles.length-1;i>=0;i--){const q=particles[i];q.life-=dt;q.x+=q.vx*dt;q.y+=q.vy*dt;q.vx*=Math.pow(.04,dt);q.vy*=Math.pow(.04,dt);if(q.life<=0){particles.splice(i,1);continue}ctx.globalAlpha=Math.min(1,q.life*3);ctx.fillStyle='#ffd166';ctx.beginPath();ctx.arc(q.x,q.y,q.r,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1}
  if(flash>0){ctx.fillStyle=`rgba(255,90,125,${flash*.18})`;ctx.fillRect(0,0,W,H);flash=Math.max(0,flash-dt*2.3)}ctx.restore()
}
function drawPlayer(p,v,t){ctx.save();ctx.translate(v.x,v.y);if(!p.alive){ctx.globalAlpha=.22;ctx.beginPath();ctx.arc(0,0,18,0,Math.PI*2);ctx.fillStyle=p.color;ctx.fill();ctx.restore();return}const dash=(nowS()-p.lastDash)<.16;if(dash){ctx.globalAlpha=.22;ctx.fillStyle=p.color;ctx.beginPath();ctx.ellipse(-Math.cos(p.angle)*26,-Math.sin(p.angle)*26,28,14,p.angle,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1}if(p.shield>0){ctx.beginPath();ctx.arc(0,0,24+Math.sin(t*5)*2,0,Math.PI*2);ctx.strokeStyle='rgba(99,215,255,.9)';ctx.lineWidth=3;ctx.stroke()}ctx.rotate(p.angle);ctx.fillStyle='#d9deeb';roundRect(ctx,5,-5,26,10,4);ctx.fill();ctx.rotate(-p.angle);ctx.shadowBlur=16;ctx.shadowColor=p.color;ctx.fillStyle=p.color;ctx.beginPath();ctx.arc(0,0,18,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='#11151f';ctx.beginPath();ctx.arc(-6,-4,3.2,0,Math.PI*2);ctx.arc(6,-4,3.2,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#11151f';ctx.lineWidth=2;ctx.beginPath();ctx.arc(0,3,7,.15,Math.PI-.15);ctx.stroke();ctx.textAlign='center';ctx.font='900 12px system-ui';ctx.fillStyle='rgba(0,0,0,.7)';ctx.fillText(p.name,1,36);ctx.fillStyle='white';ctx.fillText(p.name,0,35);if(p.hp<100){ctx.fillStyle='rgba(0,0,0,.55)';roundRect(ctx,-20,42,40,5,3);ctx.fill();ctx.fillStyle='#ff668f';roundRect(ctx,-20,42,40*clamp(p.hp/100,0,1),5,3);ctx.fill()}ctx.restore()}
function roundRect(c,x,y,w,h,r){r=Math.min(r,w/2,h/2);c.beginPath();c.moveTo(x+r,y);c.arcTo(x+w,y,x+w,y+h,r);c.arcTo(x+w,y+h,x,y+h,r);c.arcTo(x,y+h,x,y,r);c.arcTo(x,y,x+w,y,r);c.closePath()}
function renderHUD(t){const p=gameState?.players?.[myId];$('#timerText').textContent=formatTime(gameState?.timeLeft??ROUND_TIME);if(p){const w=WEAPONS[p.weapon]||WEAPONS.blaster;$('#weaponText').textContent=w.name+(p.weapon!=='blaster'?' ⚡':'');$('#hpNum').textContent=Math.max(0,Math.round(p.hp||0));$('#hpBar').style.width=clamp(p.hp||0,0,100)+'%';const sw=$('#shieldWrap');if((p.shield||0)>0){sw.style.display='block';$('#shieldNum').textContent=Math.round(p.shield);$('#shieldBar').style.width=clamp((p.shield/60)*100,0,100)+'%'}else sw.style.display='none';const dashLeft=Math.max(0,2-(nowS()-(p.lastDash||-99)));const d=$('#dashPip');if(dashLeft<=0){d.textContent='DASH READY';d.classList.add('ready')}else{d.textContent='DASH '+dashLeft.toFixed(1)+'s';d.classList.remove('ready')}}
  const ps=Object.values(gameState?.players||{}).sort((a,b)=>(b.score||0)-(a.score||0));$('#scoreboard').innerHTML=ps.map(p=>`<div class="scoreRow"><span class="scoreName"><span style="color:${p.color}">●</span> ${esc(p.name)}</span><span class="scoreVal">${p.score||0}</span></div>`).join('');renderFeed();
}
function formatTime(s){s=Math.max(0,Math.ceil(s));return Math.floor(s/60)+':'+String(s%60).padStart(2,'0')}
