function startSolo(){cleanupNet();ensureAudio();isSolo=true;isHost=true;roomCode='SOLO';myId='host';gameState=newState();addPlayer('host',cleanName(),{host:true});for(let i=0;i<4;i++)addBot();startRound()}
function addBot(){if(!isHost&&!isSolo)return;if(Object.keys(gameState.players).length>=MAX_PLAYERS){toast('Room is full');return}const names=['Waffle','Gremlin','Bingus','Turbo','Meatball','Goblin','Skrrt','Noodle','Bonk','Crumb'];addPlayer('bot-'+(++botCounter),names[(botCounter-1)%names.length],{bot:true})}
function startRound(){if(!isHost&&!isSolo)return;localInput.up=localInput.down=localInput.left=localInput.right=localInput.fire=false;if(Object.keys(gameState.players).length<2){toast('Add a bot or wait for a friend');return}gameState.phase='playing';gameState.timeLeft=ROUND_TIME;gameState.startedAt=nowS();gameState.stormRadius=325;gameState.winner=null;gameState.projectiles=[];gameState.pickups=[];gameState.meteors=[];gameState.lastPickup=0;gameState.lastMeteor=0;for(const p of Object.values(gameState.players)){p.score=0;p.deaths=0;respawn(p,true)}
  setScreen(gameScreen);$('#endOverlay').classList.remove('show');$('#roomHud').textContent=isSolo?'SOLO CHAOS':'ROOM '+roomCode;beep('start');centerMessage('GO!',900);if(isHost)sendAll({type:'start'});lastSim=performance.now();broadcastAcc=0;cancelAnimationFrame(simRAF);simRAF=requestAnimationFrame(simLoop);cancelAnimationFrame(renderRAF);lastRender=performance.now();renderRAF=requestAnimationFrame(renderLoop)}
function respawn(p,instant=false){const s=spawnPoint();p.x=s.x;p.y=s.y;p.vx=p.vy=0;p.hp=100;p.shield=0;p.alive=true;p.respawnAt=0;p.weapon='blaster';p.weaponUntil=0;p.lastHitBy=null;p.lastHitAt=0;p.lastShot=-99;p.lastDash=-99;if(!instant)emitEvent('respawn',{player:p.id})}
function endRound(){if(gameState.phase!=='playing')return;gameState.phase='ended';const ps=Object.values(gameState.players).sort((a,b)=>b.score-a.score||a.deaths-b.deaths);gameState.winner=ps[0]?.id||null;emitEvent('roundEnd',{winner:gameState.winner,name:ps[0]?.name||'Nobody'});if(isHost)sendAll({type:'state',state:serializeState()});showEnd()}
function showEnd(){const p=gameState?.players?.[gameState.winner];$('#endWinner').textContent=p?(p.name+' wins with '+p.score+' KOs!'):'Round complete';$('#rematchBtn').style.display=(isHost||isSolo)?'inline-block':'none';$('#endOverlay').classList.add('show')}

function simLoop(t){if(!gameState||gameState.phase!=='playing')return;const dt=Math.min(.035,Math.max(.001,(t-lastSim)/1000||.016));lastSim=t;simulate(dt,t/1000);broadcastAcc+=dt;if(isHost&&!isSolo&&broadcastAcc>=.05){broadcastAcc=0;sendAll({type:'state',state:serializeState()})}simRAF=requestAnimationFrame(simLoop)}
function simulate(dt,t){gameState.timeLeft=Math.max(0,ROUND_TIME-(t-gameState.startedAt));const progress=1-gameState.timeLeft/ROUND_TIME;gameState.stormRadius=325-145*Math.pow(progress,1.25);
  for(const p of Object.values(gameState.players)){if(p.bot&&p.alive)botThink(p,t);if(!p.alive){if(t>=p.respawnAt&&gameState.phase==='playing')respawn(p);continue}stepPlayer(p,dt,t)}
  stepProjectiles(dt,t);stepPickups(t);stepMeteors(dt,t);maybeSpawnPickup(t);maybeSpawnMeteor(t);
  if(gameState.timeLeft<=0||Object.values(gameState.players).some(p=>p.score>=WIN_SCORE))endRound();
}
function botThink(p,t){let best=null,bd=1e18;for(const q of Object.values(gameState.players)){if(q.id===p.id||!q.alive)continue;const d=dist2(p,q);if(d<bd){bd=d;best=q}}if(!best)return;const dx=best.x-p.x,dy=best.y-p.y,d=Math.sqrt(bd)||1;p.input.aim=Math.atan2(dy,dx);p.input.fire=bd<520*520;const side=Math.sin(t*1.8+p.id.length)>0?1:-1;const tx=dx/d+(-dy/d)*side*.72,ty=dy/d+(dx/d)*side*.72;p.input.left=tx<-.18;p.input.right=tx>.18;p.input.up=ty<-.18;p.input.down=ty>.18;if((bd<150*150||Math.random()<.003)&&t-p.lastDash>2.3)p.input.dashSeq++}
function stepPlayer(p,dt,t){const input=p.id===myId&&isHost?localInput:p.input||{};let mx=(input.right?1:0)-(input.left?1:0),my=(input.down?1:0)-(input.up?1:0);const mag=Math.hypot(mx,my)||1;mx/=mag;my/=mag;p.angle=Number.isFinite(input.aim)?input.aim:p.angle;
  if(input.dashSeq!==p.lastDashSeq&&t-p.lastDash>2.0){p.lastDashSeq=input.dashSeq;p.lastDash=t;let dx=mx,dy=my;if(Math.hypot(dx,dy)<.1){dx=Math.cos(p.angle);dy=Math.sin(p.angle)}p.vx=dx*850;p.vy=dy*850;emitEvent('dash',{player:p.id,x:p.x,y:p.y})}
  const dashing=t-p.lastDash<.16, speed=dashing?720:255, accel=dashing?11:15;const tvx=mx*speed,tvy=my*speed;p.vx+=(tvx-p.vx)*Math.min(1,accel*dt);p.vy+=(tvy-p.vy)*Math.min(1,accel*dt);p.x+=p.vx*dt;p.y+=p.vy*dt;p.x=clamp(p.x,24,W-24);p.y=clamp(p.y,24,H-24);
  const dc=Math.hypot(p.x-CX,p.y-CY);if(dc>gameState.stormRadius){damagePlayer(p,22*dt,null,t,0)}
  if(p.weapon!=='blaster'&&t>p.weaponUntil)p.weapon='blaster';if(input.fire)tryShoot(p,t)
}
function tryShoot(p,t){const w=WEAPONS[p.weapon]||WEAPONS.blaster;if(t-p.lastShot<w.rate)return;p.lastShot=t;for(let i=0;i<w.count;i++){const offset=w.count===1?rand(-w.spread,w.spread):(-w.spread/2)+(w.spread*(i/(w.count-1)));const a=p.angle+offset+rand(-.012,.012);gameState.projectiles.push({id:++projectileCounter,owner:p.id,x:p.x+Math.cos(a)*24,y:p.y+Math.sin(a)*24,vx:Math.cos(a)*w.speed,vy:Math.sin(a)*w.speed,damage:w.damage,life:w.life,radius:w.radius,rocket:!!w.rocket,weapon:p.weapon})}emitEvent('shoot',{player:p.id,weapon:p.weapon,x:p.x,y:p.y})}
function stepProjectiles(dt,t){for(let i=gameState.projectiles.length-1;i>=0;i--){const b=gameState.projectiles[i];b.life-=dt;b.x+=b.vx*dt;b.y+=b.vy*dt;let hit=null;if(b.life<=0||b.x<0||b.x>W||b.y<0||b.y>H){if(b.rocket)explodeRocket(b,t);gameState.projectiles.splice(i,1);continue}for(const p of Object.values(gameState.players)){if(!p.alive||p.id===b.owner)continue;const rr=18+b.radius;if((p.x-b.x)**2+(p.y-b.y)**2<rr*rr){hit=p;break}}if(hit){if(b.rocket)explodeRocket(b,t);else{damagePlayer(hit,b.damage,b.owner,t,125);emitEvent('hit',{player:hit.id,owner:b.owner,x:hit.x,y:hit.y})}gameState.projectiles.splice(i,1)}}}
function explodeRocket(b,t){emitEvent('boom',{x:b.x,y:b.y});for(const p of Object.values(gameState.players)){if(!p.alive||p.id===b.owner)continue;const d=Math.hypot(p.x-b.x,p.y-b.y);if(d<105){const mult=1-d/140;damagePlayer(p,b.damage*Math.max(.28,mult),b.owner,t,250*Math.max(.3,mult))}}}
function damagePlayer(p,amount,owner,t,knock){if(!p.alive)return;if(t-p.lastDash<.13)return;let a=amount;if(p.shield>0){const use=Math.min(p.shield,a);p.shield-=use;a-=use}p.hp-=a;if(owner){p.lastHitBy=owner;p.lastHitAt=t;const o=gameState.players[owner];if(o&&knock){const dx=p.x-o.x,dy=p.y-o.y,d=Math.hypot(dx,dy)||1;p.vx+=dx/d*knock;p.vy+=dy/d*knock}}if(p.hp<=0)killPlayer(p,owner,t)}
function killPlayer(p,owner,t){if(!p.alive)return;p.alive=false;p.hp=0;p.deaths++;p.respawnAt=t+1.45;let killer=owner;if(!killer&&p.lastHitBy&&t-p.lastHitAt<4)killer=p.lastHitBy;if(killer&&killer!==p.id&&gameState.players[killer])gameState.players[killer].score++;emitEvent('kill',{victim:p.id,killer:killer||null,x:p.x,y:p.y})}
function maybeSpawnPickup(t){if(t-gameState.lastPickup<4.7||gameState.pickups.length>=4)return;gameState.lastPickup=t;const kinds=['rapid','scatter','rocket','shield','heal'];const kind=kinds[Math.floor(Math.random()*kinds.length)],s=spawnPoint();gameState.pickups.push({id:++pickupCounter,kind,x:s.x,y:s.y})}
function stepPickups(t){for(let i=gameState.pickups.length-1;i>=0;i--){const u=gameState.pickups[i];let got=null;for(const p of Object.values(gameState.players)){if(!p.alive)continue;if((p.x-u.x)**2+(p.y-u.y)**2<34*34){got=p;break}}if(got){if(u.kind==='shield')got.shield=Math.min(60,got.shield+45);else if(u.kind==='heal')got.hp=Math.min(100,got.hp+42);else{got.weapon=u.kind;got.weaponUntil=t+12}emitEvent('pickup',{player:got.id,pickupKind:u.kind,x:u.x,y:u.y});gameState.pickups.splice(i,1)}}}
function maybeSpawnMeteor(t){if(gameState.timeLeft>82)return;if(t-gameState.lastMeteor<rand(3.3,5.2)||gameState.meteors.length>=3)return;gameState.lastMeteor=t;const a=Math.random()*Math.PI*2,r=rand(30,gameState.stormRadius-20);gameState.meteors.push({id:++meteorCounter,x:CX+Math.cos(a)*r,y:CY+Math.sin(a)*r,t:1.25})}
function stepMeteors(dt,t){for(let i=gameState.meteors.length-1;i>=0;i--){const m=gameState.meteors[i];m.t-=dt;if(m.t<=0){emitEvent('meteor',{x:m.x,y:m.y});for(const p of Object.values(gameState.players)){if(!p.alive)continue;const d=Math.hypot(p.x-m.x,p.y-m.y);if(d<105)damagePlayer(p,45*Math.max(.35,1-d/130),null,t,0)}gameState.meteors.splice(i,1)}}}
function serializeState(){return {phase:gameState.phase,timeLeft:gameState.timeLeft,stormRadius:gameState.stormRadius,winner:gameState.winner,players:Object.values(gameState.players).map(p=>({id:p.id,name:p.name,x:p.x,y:p.y,vx:p.vx,vy:p.vy,angle:p.angle,hp:p.hp,shield:p.shield,score:p.score,deaths:p.deaths,alive:p.alive,respawnAt:p.respawnAt,color:p.color,weapon:p.weapon,weaponUntil:p.weaponUntil,lastDash:p.lastDash,bot:p.bot,host:p.host})),projectiles:gameState.projectiles,pickups:gameState.pickups,meteors:gameState.meteors}}
function applySnapshot(s){if(!s)return;if(!gameState)gameState=newState();gameState.phase=s.phase;gameState.timeLeft=s.timeLeft;gameState.stormRadius=s.stormRadius;gameState.winner=s.winner;const seen=new Set();for(const p of s.players){seen.add(p.id);if(!gameState.players[p.id])gameState.players[p.id]={...p};else Object.assign(gameState.players[p.id],p)}for(const id of Object.keys(gameState.players))if(!seen.has(id))delete gameState.players[id];gameState.projectiles=s.projectiles||[];gameState.pickups=s.pickups||[];gameState.meteors=s.meteors||[];if(gameState.phase==='ended'){showEnd()}if(!renderRAF){lastRender=performance.now();renderRAF=requestAnimationFrame(renderLoop)}}
